//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int Id_cita { get; set; }
        public string Nombre_Propietario { get; set; }
        public Nullable<int> Id_TipoAnimal { get; set; }
        public string Raza { get; set; }
        public Nullable<System.DateTime> Fecha_cita { get; set; }
        public Nullable<System.TimeSpan> Hora_cita { get; set; }
        public string Nombre_Animal { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Id_personal { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<int> Id_estado { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual UsuarioCliente UsuarioCliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual personal personal { get; set; }
    }
}
